# Generated by Django 5.2.10 on 2026-02-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_created_at_userprofile_google_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
