# Generated by Django 5.2.10 on 2026-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_youtube_url_to_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("compressing", "Compressing Video"),
                    ("audio_converted", "Audio Converted"),
                    ("transcribed", "Transcribed"),
                    ("embedded", "Embeddings Generated"),
                    ("pdf_generated", "PDF Generated"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
    ]
