# Generated by Django 5.2.10 on 2026-03-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_transcribing_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("compressing", "Compressing Video"),
                    ("audio_converted", "Audio Converted"),
                    ("transcribing", "Transcribing Audio"),
                    ("transcribed", "Transcribed"),
                    ("embedding", "Generating Embeddings"),
                    ("embedded", "Embeddings Generated"),
                    ("generating_pdf", "Generating PDF"),
                    ("pdf_generated", "PDF Generated"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
    ]
