# Generated by Django 5.2.10 on 2026-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_embedding_and_pdf_gen_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("starting_up", "Starting Up"),
                    ("compressing", "Compressing Video"),
                    ("audio_converted", "Audio Converted"),
                    ("converting_video_to_audio", "Converting Video To Audio"),
                    ("transcribing", "Transcribing Audio"),
                    ("transcribing_audio", "Transcribing Audio"),
                    ("transcribed", "Transcribed"),
                    ("embedding", "Generating Embeddings"),
                    ("generating_embeddings", "Generating Embeddings"),
                    ("embedded", "Embeddings Generated"),
                    ("generating_pdf", "Generating PDF"),
                    ("creating_pdf", "Creating PDF"),
                    ("pdf_generated", "PDF Generated"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
    ]
